### ISSUE TITLE
Observer factory needed ?

### ISSUE THREAD

**Issue by theevann** [theevann/DD3#6]
Sent elements are not watched for modification or deletion, and we probably should ...
We may need to implement a sort of observer (ie, each time attr, remove, transform ... or such a function is called, we should check whether the object has been already sent and send new modifications to concerned browsers...)

=> This makes me think that we should save the last sent position of the shape, which may prevent us from computing recipients each time if the ctm is the same...

**Comment by davidbirchwork** [comment]
Could you have a look at the Ix and RX library and the Iobservable videos on channel9.msdn.com I think you will learn things that will be useful also look for Iqueryable

e.g. watch these:
https://channel9.msdn.com/Shows/Going+Deep/Bart-De-Smet-Interactive-Extensions-Ix
https://channel9.msdn.com/Shows/Going+Deep/Bart-De-Smet-Rx-and-Cortana
https://channel9.msdn.com/Shows/Going+Deep/Bart-De-Smet-Observations-on-IQbservable-The-Dual-of-IQueryable
I only  wish I had time to ☹

David

**Comment by theevann** [comment]
Should we watch groups that are parents of watched elements.
Do you think there is any other possibility  ? And do you think this is needed to remain coherent ?

**Comment by theevann** [comment]
We watch every elements by default now
