### ISSUE TITLE
How to deal with late messages ?

### ISSUE THREAD

**Issue by theevann** [theevann/DD3#7]
Suppose Peer 1 is sending data to Peer 2.
Peer 1 sends a first message A.
Peer 1 sends a second message B.
If message A for some reason arrives after message B, we may need to update the shape, but not necessarily. For instance, if message A was to change the color and B to move the shape, we should take A into account ; but if both were color messages then we shouldn't update).

I wonder here if there is a need for each property of each sent object to have such thing as a monotonous increasing index to check that we won't be updating it while we shouldn't. Maybe this would be a quite seldom issue and maintaining indexes on every properties of every objects will probably influence performances.
Any thoughts on that ?

**Comment by shoringfan10** [comment]
The reliable mode of RTCDataChannel of WebRTC might help to guarantee the in-order delivery of messages. In their test, the performance for reliable and unreliable modes are about the same. [1] 

[1] http://www.html5rocks.com/en/tutorials/webrtc/datachannels/
(also including how to configure the data channel, but not for PeerJS)

**Comment by shoringfan10** [comment]
The reliable mode of RTCDataChannel of WebRTC might help to guarantee the in-order delivery of messages. In their test, the performance for reliable and unreliable modes are about the same. [1]

[1] http://www.html5rocks.com/en/tutorials/webrtc/datachannels/
(also including how to configure the data channel, but not for PeerJS)


Regards,

Xiaoping


________________________________

**Comment by theevann** [comment]
Peer.js has a reliable mode that must enable the WebRTC mode. I activated it but indeed : 

> Performance for both modes is about the same when there are no packet losses. However, in reliable mode **a lost packet will cause other packets to get blocked behind** it, and the lost packet might be stale by the time it is retransmitted and arrives.    

So with the reliable mode, this is not an issue anymore - but do you think it's safe to work on reliable mode ? I'm not sure what's the best as the visualization quality may then get worse.

Thanks for the useful link !

**Comment by shoringfan10** [comment]
Hi Evann,

To avoid the unnecessary blocking, maybe we could multiplex the unreliable connection between a pair of peers. Namely, we might be able to create multiple labelled data channels in one connection [1], or we could attach a msg type (move/color) to each message. 

In terms of visualization quality, we could potentially have two types of visible effects for the network delay or loss. The first one, if we keep messages blocked and in-order, and then play faster to catch up when the lost one is received. And the second one, if we allow to skip few frames of changing (e.g. gradually change color) when few allowed interval of the same type (e.g. all color) messages are lost. 

[1] https://github.com/peers/peerjs/issues/25

Xiaoping
