### ISSUE TITLE
About transitions...

### ISSUE THREAD

**Issue by theevann** [theevann/DD3#9]
After reading and thinking, here are my thoughts about how he should start to try implementing transitions in dd3.
# 
1. We need to send transitions:
   If we don't send transitions, we will need to watch the object for attributes changes. According to d3's transitions code, these changes will happen every frame (every ~17 ms) and if we want to have smooth and coherent transitions we need to send changes through the network at a this very high rate - and this for every properties and every objects transitioned.
2. At the beginning, we can offer a basic support only for these functions:
   duration, delay, attr, style, ease
3. The way I see we can do that is:
   - to 'listen' for the selection.transition function to be triggered, we then set a listener for the start event (we cannot do differently because transition may be cancelled before start).
   - to 'listen' for the functions: attr, style, ease [and if given arguments are functions, register them to be applied during the start event].
   - during the start event: to apply the registered functions (if any) in order to only send final values (never send functions !), to save the time of start [in the global context].
   - to send the transition for each element giving (the element id, the final value, the time the transition was launched) to current recipients (if any)
   - on the reception side, to set a duration equal to the initial duration but to set a negative delay equal to the difference between start time and current time. 
4. The question of whom ?
   - Currently, to send an object, we use the dd3 method send(). Very soon will be implemented an basic observer to 'watch' a previously sent objects for modifications.
   - I think that we should automatically check any transition for sending but send only to watched objects.
   - If, at the beginning of a transition, an object doesn't have recipients, it doesn't mean it won't have recipients later on during the transition. (If position changes).  
     **I have a open question here : Should we try to guess in advance who will be all the recipients (using the ease function and the final parameter) or should we rather try to detect a move of the shape entering in a new browser and send the transition then ?**  
     Watching all transitioned objects might be degrading performance of the visualization, but I am not sure it's possible to get in advanced all recipients (and to be sure not to forget any !!!)  

So _Help Needed !_

**Comment by shoringfan10** [comment]
Hi Evann,

For the open question here, it might be better to guess the potential recipients in advance by calculating the final parameter. Thus, the recipients might have more time to prepare and 'wait' to play their parts. Comparing with detecting of entering a new browser, on-the-fly detecting might cost more visualization quality due to the uncertainty of network delay, but it could be a good backup for the unlucky guess.

Xiaoping
